### ISSUE TITLE
Transferable support

### ISSUE THREAD

**Issue by jakubwolny** [dumbmatter/promise-worker-bi#1]
Would you consider adding another option to .postMessage method to support Transferable objects? 

Motivation:
Transferring ownership of an ArrayBuffer is much faster than "structured-cloning" used for typical Worker communication. It is supported natively by MessagePort so both WebWorker and SharedWorker could use that.

Reference:
https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage
https://developer.mozilla.org/en-US/docs/Web/API/Transferable

**Comment by dumbmatter** [comment]
I don't personally have a use case for transferable objects so I probably won't add support myself in the near future, but I'd happily accept a PR if it's not too complicated.

Also, depending on your needs, [another fork of promise-worker might be good enough for you already](https://github.com/terikon/promise-worker-transferable). Compared to [the original promise-worker](https://github.com/nolanlawson/promise-worker), I mainly just added shared worker support and the ability to initiate messages in the worker.

Also if you haven't seen them, check out https://github.com/GoogleChromeLabs/comlink and https://github.com/GoogleChromeLabs/clooney they are more recent libraries aimed at solving similar problems, you might like their APIs even better :)

**Comment by jakubwolny** [comment]
Thank you for the fast answer! I already started working on a PR but I wanted to ask first.

Yes, currently I'm a happy user of promise-worker-transferable fork but it works only for WebWorkers, not SharedWorkers. And probably I will need to use SharedWorkers soon.

I might be wrong but in both projects you suggested I could't find support for SharedWorkers.

**Comment by dumbmatter** [comment]
You're probably right about the lack of shared worker support elsewhere. My impression is that I'm basically the only person who uses shared workers, so I'm happy that you might as well! It's a very powerful API, shame about the browser support though, especially since [shared workers are kind of broken in Firefox currently](https://stackoverflow.com/questions/47414543/firefox-quantum-sharedworker-not-work).

**Comment by FluffyDiscord** [comment]
pull request #4

**Comment by dumbmatter** [comment]
I finally addressed this in version 4.1.0

**Comment by jakubwolny** [comment]
Thank you for the update! For a time being I was forced to use `promise-worker-transferable` but I will consider switching back to this project since it's much better maintained.

**Comment by dumbmatter** [comment]
Wow, a thank you within 10 hours after fixing a 4 year old issue, I love it!
